import os
import subprocess
import argparse
from pathlib import Path
from datetime import datetime

class TheShredder:
    """
    NAUTILUS Media Digest Module.
    Extracts transcripts from video/audio using Echo (Whisper-based) 
    and packages them for the Knowledge Graph.
    """

    def __init__(self, echo_path: str):
        self.echo_path = echo_path

    def process_media(self, file_path: Path):
        """Processes a single media file: Transcription -> Markdown."""
        print(f"[*] Shredding: {file_path.name}")
        
        transcript_path = file_path.with_suffix(".transcript.md")
        
        if transcript_path.exists():
            print(f"[-] Skipping (already exists): {file_path.name}")
            return transcript_path

        try:
            # Integration with newly built Echo CLI
            cmd = [self.echo_path, "--transcribe-file", str(file_path), "--output", str(transcript_path)]
            subprocess.run(cmd, check=True)
            
            print(f"[+] Real transcript generated: {transcript_path.name}")
            return transcript_path
            
        except Exception as e:
            print(f"[!] Error shredding {file_path.name}: {e}")
            return None

    def _create_stub_transcript(self, source: Path, target: Path):
        """Creates a structured Markdown file for the Knowledge Graph."""
        now = datetime.now().isoformat()
        content = f"""---
type: transcript
source: {source.name}
processed_at: {now}
status: manual_verify_needed
resonance: ⚡
---

# Transcript: {source.stem}

> [!NOTE]
> This is an automated digest generated by **The Shredder** using **Echo**.
> Original video preserved at: `{source.absolute()}`

## 📝 Content
(Transcription content will be populated by Echo CLI)

## 🏷️ Tags
#transcript #unprocessed #echo-digest
"""
        target.write_text(content, encoding="utf-8")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="NAUTILUS Media Shredder")
    parser.add_argument("--dir", type=str, help="Directory to scan")
    parser.add_argument("--file", type=str, help="Single file to process")
    args = parser.parse_args()

    shredder = TheShredder(echo_path="C:/telo/Efforts/On/echo/target/release/echo.exe")
    
    if args.file:
        shredder.process_media(Path(args.file))
    elif args.dir:
        dir_path = Path(args.dir)
        for media_file in dir_path.rglob("*"):
            if media_file.suffix.lower() in [".mp4", ".mkv", ".mov", ".mp3", ".wav", ".m4a"]:
                shredder.process_media(media_file)
    else:
        # Default scan paths
        scan_paths = [
            "C:/telo/Calendar/Inbox",
            "C:/Users/sasha/Downloads/Notes_ACE",
            "C:/Users/sasha/Downloads/Notes_ACE_Backup_Originals"
        ]
        for path_str in scan_paths:
            path = Path(path_str)
            if path.exists():
                print(f"[*] Scanning: {path}")
                for media_file in path.rglob("*"):
                    if media_file.suffix.lower() in [".mp4", ".mkv", ".mov", ".mp3", ".wav", ".m4a"]:
                        shredder.process_media(media_file)
